apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name:  ${{values.app_name}}
  description: ${{values.app_description}}
  # Example for optional annotations
  annotations:
    github.com/project-slug: dmaproz/${{values.app_name}}
spec:
  type: service
  owner: development
  lifecycle: experimental